<?xml version="1.0" encoding="UTF-8"?><map xmlns:css2fo="http://www.oxygenxml.com/css2fo" xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot" xmlns:ditaarch="http://dita.oasis-open.org/architecture/2005/" xmlns:nd="http://www.oxygenxml.com/css2fo/named-destinations" xmlns:opentopic="http://www.idiominc.com/opentopic" xmlns:opentopic-index="http://www.idiominc.com/opentopic/index" xmlns:oxy="http://www.oxygenxml.com/extensions/author" xmlns:xs="http://www.w3.org/2001/XMLSchema" cascade="merge" class="- map/map " ditaarch:DITAArchVersion="1.3" domains="(map mapgroup-d) (topic abbrev-d) (topic delay-d) a(props deliveryTarget) (map ditavalref-d) (map glossref-d) (topic hazard-d) (topic hi-d) (topic indexing-d) (topic markup-d) (topic pr-d) (topic relmgmt-d) (topic sw-d) (topic ui-d) (topic ut-d) (topic markup-d xml-d)" specializations="@props/deliveryTarget" xtrc="map:1;3:6" xtrf="file:/C:/Users/ktcri/OneDrive/Desktop/Harness/harness_user_guide_for_paypal.ditamap" xml:lang="en"><oxy:front-page class="- front-page/front-page "><oxy:front-page-title class="- front-page/front-page-title "><title xmlns:ot-placeholder="http://suite-sol.com/namespaces/ot-placeholder" class="- topic/title ">Harness User Guide for PayPal</title></oxy:front-page-title></oxy:front-page><opentopic:map xmlns:ot-placeholder="http://suite-sol.com/namespaces/ot-placeholder" class="- toc/toc "><oxy:toc-title class="- toc/title " empty="true"/>
    <title class="- topic/title ">Harness User Guide for PayPal</title>
    <topichead is-chapter="true" class="+ map/topicref mapgroup-d/topichead " navtitle="Introduction"><topicmeta class="- map/topicmeta "><navtitle class="- topic/navtitle " href="#d70e14">Introduction</navtitle></topicmeta><topicref class="- map/topicref " href="#unique_1" type="concept"><topicmeta class="- map/topicmeta " data-topic-id="concept_jth_wwj_53c"><resourceid appid="concept_jth_wwj_53c" class="- topic/resourceid " oxy-source="topic"/><navtitle href="#unique_1" class="- topic/navtitle ">Introduction</navtitle><?ditaot gentext?><?ditaot genshortdesc?><shortdesc class="- map/shortdesc ">Harness.io manages the full lifecycle of the CI/CD (Continuous Integration/Continuous         Deployment) process. You can define and automate your build, test, and deployment pipelines         using easy-toc-configure YAML files, and the pipelines can also be version-controlled,         making updates and changes simpler. Harness supports parallel execution of jobs, allowing         you to run builds, tests, and deployments simultaneously.</shortdesc></topicmeta></topicref><topichead class="+ map/topicref mapgroup-d/topichead " navtitle="Access and Roles"><topicmeta class="- map/topicmeta "><navtitle class="- topic/navtitle " href="#d70e26">Access and Roles</navtitle></topicmeta></topichead><topichead class="+ map/topicref mapgroup-d/topichead " navtitle="Training, Support, Resources"><topicmeta class="- map/topicmeta "><navtitle class="- topic/navtitle " href="#d70e27">Training, Support, Resources</navtitle></topicmeta></topichead></topichead>
    <topichead is-chapter="true" class="+ map/topicref mapgroup-d/topichead " navtitle="Onboard Your Application"><topicmeta class="- map/topicmeta "><navtitle class="- topic/navtitle " href="#d70e29">Onboard Your Application</navtitle></topicmeta></topichead>
</opentopic:map><topic xmlns:ot-placeholder="http://suite-sol.com/namespaces/ot-placeholder" break-before="true" is-chapter="true" class="+ topic/topic pdf2-d/placeholder " id="d70e14" topicrefclass="+ map/topicref mapgroup-d/topichead "><title class="- topic/title "><ph class="- topic/ph topic/title-wrapper ">Introduction</ph></title><concept class="- topic/topic concept/concept " id="unique_1" topicrefclass="- map/topicref " nd:nd-id="concept_jth_wwj_53c" oid="concept_jth_wwj_53c" specializations="@props/deliveryTarget">
    <title class="- topic/title "><ph class="- topic/ph topic/title-wrapper ">Introduction</ph></title>
    <shortdesc class="- topic/shortdesc ">Harness.io manages the full lifecycle of the CI/CD (Continuous Integration/Continuous
        Deployment) process. You can define and automate your build, test, and deployment pipelines
        using easy-toc-configure YAML files, and the pipelines can also be version-controlled,
        making updates and changes simpler. Harness supports parallel execution of jobs, allowing
        you to run builds, tests, and deployments simultaneously.</shortdesc>
</concept><topic class="+ topic/topic pdf2-d/placeholder " id="d70e26" topicrefclass="+ map/topicref mapgroup-d/topichead "><title class="- topic/title "><ph class="- topic/ph topic/title-wrapper ">Access and Roles</ph></title></topic><topic class="+ topic/topic pdf2-d/placeholder " id="d70e27" topicrefclass="+ map/topicref mapgroup-d/topichead "><title class="- topic/title "><ph class="- topic/ph topic/title-wrapper ">Training, Support, Resources</ph></title></topic></topic><topic xmlns:ot-placeholder="http://suite-sol.com/namespaces/ot-placeholder" break-before="true" is-chapter="true" class="+ topic/topic pdf2-d/placeholder " id="d70e29" topicrefclass="+ map/topicref mapgroup-d/topichead "><title class="- topic/title "><ph class="- topic/ph topic/title-wrapper ">Onboard Your Application</ph></title></topic></map>